Add parent class
hmcts/probate-back-office pull request #1214
Opened 2020-11-17 12:59 UTC by meganaslattery

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPB-922

### Change description ###

Refactor CaseData.java class to add more fields

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2020-11-17 14:02 UTC, jackmunkonge requested changes

2020-11-17 14:02 UTC, jackmunkonge commented on build.gradle
> +        lombok                          : '1.18.14',
Check the lombok changelog, it says not to use this version as it's broken and to use 1.18.16

2020-11-17 14:03 UTC, meganaslattery commented on build.gradle
> +        lombok                          : '1.18.14',
Ok nice

2020-11-17 14:03 UTC, meganaslattery commented on build.gradle
> +        lombok                          : '1.18.14',
Had to upgrade for the @Jacksonized annotation

2020-11-19 13:15 UTC, jackmunkonge approved these changes

2020-11-19 13:37 UTC, meganaslattery commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseData.java
>      private final List<CollectionMember<Document>> probateNotificationsGenerated = new ArrayList<>();
#

2020-11-24 13:43 UTC, vinceholt approved these changes

2020-11-24 13:43 UTC, vinceholt commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseDataParent.java
> +}
COULD: could have a tri class hieararchy, rename parent to CaseDataBase and fill that with all existing fields. Then  add a class that extends that, possibly called AdditionalCaseDataFields which would include new field, then have a class that extends that called CaseData with no fields

2020-11-26 17:21 UTC, KleoG approved these changes

2020-12-02 11:34 UTC, merged