DTSPB-1092-Send Will with 'Grant of Probate'
hmcts/probate-back-office pull request #1325
Opened 2021-02-03 15:58 UTC by stelioskalo

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-1092

### Change description ###
Send the copy of the final will with the Grant of Probate

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-02-04 12:59 UTC, sanjayparekh-hmcts requested changes

2021-02-04 12:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/BulkPrintService.java
> +        String encodedWillDocument = getPdfAsBase64EncodedString(findWillService.findWill(callbackRequest), authHeaderValue, callbackRequest);
probably should try to pass in casedetails or casedata rather than the request

2021-02-04 12:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/BulkPrintService.java
> +        uk.gov.hmcts.reform.sendletter.api.model.v3.Document willDocument = new uk.gov.hmcts.reform.sendletter.api.model.v3.Document(encodedWillDocument, 1);
what if there is no will?

2021-02-04 12:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/FindWillService.java
> +        CaseData caseData = callbackRequest.getCaseDetails().getData();
pass in casedata not request

2021-02-04 12:59 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/template/pdf/PDFManagementService.java
> +    public Document generateAndUpload(String json, DocumentType documentType) {
why did you need to make this public?

2021-03-03 11:59 UTC, isha2040 commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/documents/SolBaCcdServiceDocumentsTests.java
> -        String jsonAsString = getJsonFromFile("/document/rePrintDefaultGrantOfProbate.json");
is there a reason to remove this json ?

2021-03-03 12:02 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/documents/SolBaCcdServiceDocumentsTests.java
> -        String jsonAsString = getJsonFromFile("/document/rePrintDefaultGrantOfProbate.json");
it was just never being used

2021-03-03 13:58 UTC, isha2040 commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +      "outsideUKGrantCopies": null,
would this be a valid entry after negative values check ?

2021-03-03 13:58 UTC, isha2040 commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +            "address": {
please add some appropriate address

2021-03-03 13:58 UTC, isha2040 commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +      "solsSolicitorIsMainApplicant": null,
should it be changed to some better values

2021-03-03 13:58 UTC, isha2040 commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +      "deceasedAnyOtherNames": "PUBLIC",
please change it to some logical values rather than Public. Please try to incorporate some scenario based names or fields to improve quality of tests if possible

2021-03-03 13:58 UTC, isha2040 commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWills.json
> +      "deceasedForenames": "PUBLIC",
Could we add some better test data than 'Public' please

2021-03-03 14:09 UTC, isha2040 approved these changes

2021-03-03 14:16 UTC, sanjayparekh-hmcts commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +      "outsideUKGrantCopies": null,
done

2021-03-03 14:17 UTC, sanjayparekh-hmcts commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +            "address": {
done

2021-03-03 14:17 UTC, sanjayparekh-hmcts commented on src/functionalTest/resources/json/personalPayloadNotificationsWithWillSelection.json
> +      "solsSolicitorIsMainApplicant": null,
done

2021-06-08 13:27 UTC, closed without merging