DTSPB-1519 Add stopped date if case is stopped when updating task list
hmcts/probate-back-office pull request #1394
Opened 2021-03-08 15:14 UTC by itoulou

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-1519

### Change description ###
The caseworker actioned the QA step after the Mark as ready to issue but failed the QA step. This leads to the case being stopped. Just like a stopped case, the date when the case was stopped does not show and instead the word Unknown is displayed.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-03-09 15:47 UTC, sanjayparekh-hmcts requested changes

2021-03-09 15:47 UTC, sanjayparekh-hmcts commented on ccdImports/configFiles/CCD_Probate_Backoffice/CaseEvent.json
> +  {"LiveFrom": "01/01/2017", "CaseTypeID": "GrantOfRepresentation", "ID": "boFailQA", "Name": "Fail QA", "Description": "Fail QA and mark the case as stopped", "DisplayOrder": 47, "PreConditionState(
prbabaly better to call it fail-qa not failQA

2021-03-09 15:47 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/caseprogress/SolCcdCaseProgressAdmonWillTests.java
> +        String expectedHtml = "<div class=\"width-50\">\n\n<h2 class=\"govuk-heading-l\">Case progress</h2>\n\n"
you should put this expected response into some resource file + read it as in other tests

2021-03-09 15:47 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/caseprogress/SolCcdCaseProgressIntestacyTests.java
> +        String expectedHtml = "<div class=\"width-50\">\n\n<h2 class=\"govuk-heading-l\">Case progress</h2>\n\n"
put response in resource file

2021-03-09 15:47 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/caseprogress/SolCcdCaseProgressTests.java
> +        String expectedHtml = "<div class=\"width-50\">\n\n<h2 class=\"govuk-heading-l\">Case progress</h2>\n\n"
same here

2021-03-09 15:47 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/BusinessValidationController.java
> +    @PostMapping(path = "/failQA", consumes = APPLICATION_JSON_VALUE, produces = {APPLICATION_JSON_VALUE})
fail-qa

2021-03-10 14:15 UTC, sanjayparekh-hmcts approved these changes

2021-03-15 09:19 UTC, isha2040 approved these changes

2021-06-30 13:45 UTC, merged