Dtspb 1174 supplementary evid to yes
hmcts/probate-back-office pull request #1441
Opened 2021-03-25 15:05 UTC by AbdullahShahHMCTS

### JIRA link (if applicable) ###
DTSPB-1174

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-03-31 08:49 UTC, isha2040 commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseData.java
> +            message = "{solsSolicitorFirmNameIsNull}")
Are you sure you have the Correct Checkstyle file in your IDE configured ? There seem to be no code changes in this file but only formatting . It should all be correct as this must have come from master . Please check again.

2021-03-31 08:52 UTC, isha2040 commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +        if (NO.toLowerCase().equals(caseData.getEvidenceHandled().toLowerCase())) {
Please try and use equalsIgnoreCase rather than this current implementation.

2021-03-31 09:45 UTC, sanjayparekh-hmcts requested changes

2021-03-31 09:45 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +        if (NO.toLowerCase().equals(caseData.getEvidenceHandled().toLowerCase())) {
I am not sure this is in the right place - shouldn't it be in the /generate-grant api ?

2021-03-31 09:45 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/documents/SolBaCcdServiceDocumentsTests.java
> +                .body(utils.getJsonFromFile(GENERATE_LETTER_PAYLOAD))
surely it should be /generate-grant api?

2021-03-31 10:08 UTC, AbdullahShahHMCTS commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/documents/SolBaCcdServiceDocumentsTests.java
> +                .body(utils.getJsonFromFile(GENERATE_LETTER_PAYLOAD))
yes, not sure how I got to this endpoint now

2021-03-31 11:17 UTC, AbdullahShahHMCTS commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseData.java
> +    private String evidenceHandled;
This is the variable added, the rest of the formatting needs to be reverted

2021-04-01 12:15 UTC, vinceholt approved these changes

2021-06-01 13:18 UTC, sanjayparekh-hmcts requested changes

2021-06-01 13:18 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +        if (NO.equalsIgnoreCase(caseData.getEvidenceHandled())) {
you could probably put this on a single line

2021-06-03 13:02 UTC, sanjayparekh-hmcts requested changes

2021-06-03 13:02 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +        if (NO.equalsIgnoreCase(caseData.getEvidenceHandled())) {
Actually - this is not right - this needs to be put in one of the transformers + then you can make the evidenceHandled var a final

2021-06-03 13:02 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseData.java
> +    private String evidenceHandled;
this should really be a final - any reason why not?

2021-06-04 13:57 UTC, sanjayparekh-hmcts requested changes, later dismissed

2021-06-04 13:57 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +import static uk.gov.hmcts.probate.model.Constants.YES;
Why do we need these 2 here?

2021-06-04 13:59 UTC, isha2040 commented on src/main/java/uk/gov/hmcts/probate/controller/DocumentController.java
> +import static uk.gov.hmcts.probate.model.Constants.YES;
please compare this java file with master , dont see any of the changes made here are required . These are ununsed imports and should fail in checkstyles itself when u build

2021-06-04 14:00 UTC, isha2040 commented on src/main/java/uk/gov/hmcts/probate/model/ccd/raw/request/CaseData.java
> -    private final String evidenceHandled;
please compare this java file with master , dont see any of the changes made here are required . this file shouldnt appear in the change set for u

2021-06-07 09:18 UTC, isha2040 approved these changes

2021-06-08 09:31 UTC, isha2040 approved these changes

2021-06-08 10:04 UTC, closed without merging