DTSPB-1576: Lookup lev record by system number
hmcts/probate-back-office pull request #1705
Opened 2021-08-20 09:28 UTC by nigeldunne

JIRA link (if applicable)

https://tools.hmcts.net/jira/browse/DTSPB-1576
Change description

Lookup lev record by system number

Does this PR introduce a breaking change? (check one with "x")

[ ] Yes
[x] No

2021-09-17 12:01 UTC, sanjayparekh-hmcts requested changes

2021-09-17 12:01 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/controller/LifeEventController.java
> +        final DeathRecord deathRecord = lifeEventService.getDeathRecordById(systemNumber);
perhaps these calls belong together in their own service with the transformer call?

2021-09-17 12:01 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/DeathRecordService.java
> +        final uk.gov.hmcts.probate.model.ccd.raw.DeathRecord.DeathRecordBuilder builder
can the classes here be imported to make it more readable?

2021-09-20 16:09 UTC, nigeldunne commented on src/main/java/uk/gov/hmcts/probate/controller/LifeEventController.java
> +        final DeathRecord deathRecord = lifeEventService.getDeathRecordById(systemNumber);
Done

2021-09-20 16:10 UTC, nigeldunne commented on src/main/java/uk/gov/hmcts/probate/service/DeathRecordService.java
> +        final uk.gov.hmcts.probate.model.ccd.raw.DeathRecord.DeathRecordBuilder builder
Refactored as discussed

2021-09-21 10:45 UTC, sanjayparekh-hmcts approved these changes

2021-10-12 08:17 UTC, closed without merging