DTSPB-2335 fixed admon will condition for access to original will
hmcts/probate-back-office pull request #1723
Opened 2021-09-09 15:26 UTC by AbdullahShahHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-2335

### Change description ###
Admon will will show the correct wording on legal statement if sol has access to will

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-09-10 16:35 UTC, sanjayparekh-hmcts requested changes, later dismissed

2021-09-10 16:35 UTC, sanjayparekh-hmcts commented on src/main/resources/application.yml
> +  sdk_key: ${LAUNCHDARKLY_KEY:sdk-4d50eb6e-8400-4aa7-b4c5-8bdfc8b1d844}
I think you need to roll this back

2021-09-10 16:35 UTC, sanjayparekh-hmcts commented on src/functionalTest/java/uk/gov/hmcts/probate/functional/documents/SolBaCcdServiceDocumentsTests.java
> +        System.out.println(response);
remove this too

2021-10-07 14:46 UTC, itoulou approved these changes

2021-10-07 16:09 UTC, merged