DTSPB-2429 Changes to point prod to v11 probateman DB
hmcts/probate-back-office pull request #1861
Opened 2022-03-15 14:01 UTC by isha2040

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-2429

### Change description ###
postgres v11 migration change to prod vars

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X ] No
```

2022-03-15 14:42 UTC, sanjayparekh-hmcts approved these changes

2022-03-15 15:31 UTC, cakeben approved these changes

2022-03-16 11:10 UTC, nigeldunne requested changes
Check https://github.com/hmcts/probate-back-office/blob/DTSPB-2429-Postgres-V11-Changes/Jenkinsfile_CNP#L23

2022-03-16 16:56 UTC, nigeldunne approved these changes

2022-03-16 20:33 UTC, merged