DTSPB-2701 change email address to contact when payment duplicate
hmcts/probate-back-office pull request #1897
Opened 2022-04-27 16:46 UTC by DelythJustice

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-05-04 13:19 UTC, sanjayparekh-hmcts requested changes

2022-05-04 13:19 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/service/payments/PaymentsService.java
> +    protected static final String DUPICANT_PAYMENT_ERROR_KEY = "duplicate payment";
might be worth renaming this CONST - spelled incorrectly
Also, I dont think its good practice to make a const protected just for the purpose of a test. My attitude would be to use the actual text value in the test.. happy to be contradicted on that one

2022-05-04 15:12 UTC, sanjayparekh-hmcts approved these changes

2022-05-05 13:21 UTC, DelythJustice commented
merged lastest master and added the 'nightly' label

2022-05-31 15:42 UTC, merged