DTSPB-3516 Remove Security.sh
hmcts/probate-back-office pull request #2261
Opened 2023-04-04 11:20 UTC by MarcusHMCTS

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPB-3516

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-04-05 10:43 UTC, FeliTam requested changes

2023-04-05 10:43 UTC, FeliTam commented on dependency-check-suppressions.xml
> +        <cve>CVE-2023-20860</cve>
The same packageUrl exist already, please add the cve to those blocks (under <cve>CVE-2023-20861</cve>).
Same for all below

2023-04-11 08:26 UTC, MarcusHMCTS commented on dependency-check-suppressions.xml
> +        <cve>CVE-2023-20860</cve>
moved CVE-2023-20860 under CVE-2023-20861

2023-04-11 09:42 UTC, FeliTam approved these changes

2023-04-11 10:43 UTC, merged