DTSPB-3931 Caveat match
hmcts/probate-back-office pull request #2476
Opened 2024-01-11 15:02 UTC by IswaryaPepakayala

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2024-03-26 15:35 UTC, FeliTam requested changes
Please add the "caseMatches" to other Caveat match events in CaseEventToFields
It is around Line#220

2024-03-27 10:07 UTC, FeliTam submitted a review, later dismissed

2024-04-10 15:55 UTC, jamiealbertelli submitted a review, later dismissed

2024-04-10 16:09 UTC, FeliTam approved these changes

2024-04-10 16:27 UTC, merged