DTSPB-4138 bug fix for exception record Intestacy trigger
hmcts/probate-back-office pull request #2556
Opened 2024-04-18 09:34 UTC by GEvans-HMCTS

resolves https://tools.hmcts.net/jira/browse/DTSPB-4138

2024-04-18 09:42 UTC, FeliTam requested changes

2024-04-18 09:42 UTC, FeliTam commented on src/test/java/uk/gov/hmcts/probate/service/exceptionrecord/ExceptionRecordServiceTest.java
> +                .readValue(exceptionRecordPayloadPA1P, ExceptionRecordRequest.class);
it should be reading from exceptionRecordPayloadPA1A

2024-04-18 09:42 UTC, FeliTam commented on src/test/resources/expectedExceptionRecordDataSolicitorSingleExecutorPA1A.json
> +    { "name": "solsWillType", "value": "WillLeftAnnexed" },
solsWillType is "NoWill" for intestacy

2024-04-19 15:31 UTC, FeliTam submitted a review, later dismissed

2024-05-07 16:55 UTC, MarcusHMCTS submitted a review, later dismissed

2024-06-13 13:52 UTC, MarcusHMCTS approved these changes

2024-06-13 13:53 UTC, merged