DTSPB-4180 st application completed date
hmcts/probate-back-office pull request #2636
Opened 2024-07-11 12:48 UTC by abbasiTahir

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPB-4095

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-07-15 09:55 UTC, GEvans-HMCTS approved these changes, later dismissed

2024-07-16 08:35 UTC, FeliTam requested changes

2024-07-16 08:35 UTC, FeliTam commented on src/test/java/uk/gov/hmcts/probate/transformer/CallbackResponseTransformerTest.java
> +        assertNotNull(caseDataBuilder.applicationSubmittedDate(null));
This test doesn't make sense to me.
It should at least execute the updated 'grantRaised' method and check if the applicationSubmittedDate is set

2024-07-19 10:46 UTC, FeliTam submitted a review, later dismissed

2024-07-22 09:13 UTC, GEvans-HMCTS submitted a review, later dismissed

2024-07-31 12:00 UTC, FeliTam approved these changes

2024-07-31 14:45 UTC, merged