DTSPB-4295: Add new name diff reasons
hmcts/probate-back-office pull request #2692
Opened 2024-08-21 10:35 UTC by jamiealbertelli

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2024-08-27 09:39 UTC, GEvans-HMCTS approved these changes, later dismissed

2024-08-30 08:11 UTC, IswaryaPepakayala requested changes

2024-08-30 08:11 UTC, IswaryaPepakayala commented on src/test/java/uk/gov/hmcts/probate/transformer/CallbackResponseTransformerTest.java
> +        caseDataBuilder.primaryApplicantAliasReason("marriageOrCivilPartnership");
This should be Marriage right

2024-08-30 08:24 UTC, IswaryaPepakayala approved these changes, later dismissed

2024-10-02 08:59 UTC, IswaryaPepakayala approved these changes

2024-10-02 08:59 UTC, FeliTam approved these changes

2024-10-02 09:05 UTC, merged