DTSPB-4115 added the upload time stamp document link
hmcts/probate-back-office pull request #2695
Opened 2024-08-28 09:26 UTC by abbasiTahir

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPB-4115

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

2024-08-28 10:31 UTC, GEvans-HMCTS submitted a review, later dismissed

2024-09-10 13:31 UTC, FeliTam commented
need to revert the Jenkinsfile before merging

2024-09-23 13:52 UTC, FeliTam approved these changes

2024-10-07 15:19 UTC, FeliTam requested changes
Need to update ProbateDocumentLink model in probate-commons as well.
Otherwise, submit service will get deserialise error when there is upload_timestamp field in the case data

2024-11-28 15:09 UTC, GEvans-HMCTS submitted a review, later dismissed

2025-01-27 12:31 UTC, FeliTam approved these changes

2025-01-28 10:19 UTC, merged