Test legacy e2e flow
hmcts/probate-back-office pull request #371
Opened 2019-04-02 10:36 UTC by mhisltd

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRO-4593

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2019-04-10 14:30 UTC, douglasrice requested changes
src/test/end-to-end/paths/legacySearchPath.js

const createCaseConfig = require('src/test/end-to-end/pages/createCase/createCaseConfig.json'); never used so can be removed
I.filterCase(filterCaseConfig.list1_text, filterCaseConfig.list2_text, filterCaseConfig.list3_text); I would remove these parameters and use them within the src/test/end-to-end/pages/filterCase/filterCase.js file itself -> then this line can also be removed: 
const filterCaseConfig = require('src/test/end-to-end/pages/filterCase/filterCaseConfig');


src/test/end-to-end/pages/selectCase/selectCase.js
src/test/end-to-end/pages/search/legacyCaseSearch.js
src/test/end-to-end/pages/search/legacyCaseSearch2.js
src/test/end-to-end/pages/search/legacyCaseSearch3.js
Remove the parameters in the function (for these files) as they are not used

2019-04-11 14:31 UTC, br0kenbuild requested changes

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/saucelabs.conf.js
> +    'tests': './paths/legacySearchPath.js',
missed?

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/pages/search/legacyCaseSearch2.js
> +    I.wait(20);
why? Doug hasn't used it after any of his 18 uses of 'waitForNavigationToComplete'

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/pages/search/legacyCaseSearch2.js
> +    I.wait(20);
why? 'waitForNavigationToComplete' does also:
waitForNavigation({waitUntil: ['domcontentloaded', 'networkidle0']})

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/pages/search/legacyCaseSearch3.js
> +    I.wait(20);
same here

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/pages/selectCase/selectCase.js
> +    I.wait(20);
same here

2019-04-11 14:31 UTC, br0kenbuild commented on src/test/end-to-end/pages/search/legacyCaseSearch.js
> +    I.wait(20);
same here

2019-07-04 09:19 UTC, closed without merging