PRO-5201 PRO-4075 caveat raised notifications
hmcts/probate-back-office pull request #472
Opened 2019-05-22 10:12 UTC by RebeccaBaker

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRO-5201
https://tools.hmcts.net/jira/browse/PRO-4075

### Change description ###
Send Caveat raised notification to caveator. 
Default values for determining post or email. 
Save to notifications tab
unit tests and functional tests

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2019-05-24 08:30 UTC, sanjayparekh-hmcts requested changes

2019-05-24 08:30 UTC, sanjayparekh-hmcts commented on docker/docker-compose-with-ccd.yml
> +  ethos-repl-docmosis-service:
Not sure you actually need this one - let me know otherwise, else remove + leave the tornado one

2019-05-24 08:30 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/config/PDFServiceConfiguration.java
> +    private String hmctsFamilyLogoBase64File;
Other services are doing this, ut I keep getting told by Jamil that the image SHOULD live on the tornado server + be accessible directly. Can you investigate this please?

2019-05-24 08:30 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/model/docmosis/PdfDocumentRequest.java
> +    @JsonProperty(value = "pdfArchiveMode")
check the usag of this too - do we need it? what does it relate to?

2019-05-24 12:26 UTC, RebeccaBaker commented on docker/docker-compose-with-ccd.yml
> +  ethos-repl-docmosis-service:
removed

2019-05-28 12:35 UTC, sanjayparekh-hmcts approved these changes

2019-05-28 15:20 UTC, merged