added examine case reissue with reason
hmcts/probate-back-office pull request #509
Opened 2019-06-11 15:53 UTC by kurt-uk

**Before creating a pull request make sure that:**

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRO-5116

### Change description ###
added examine case reissue event, included order needed and reason for reissue. Added amend case details to the event options, and added new section that allows user to edit the reissue details

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2019-06-12 08:29 UTC, RebeccaBaker approved these changes

2019-06-24 08:03 UTC, sanjayparekh-hmcts approved these changes

2019-06-25 12:58 UTC, sanjayparekh-hmcts requested changes

2019-06-25 12:58 UTC, sanjayparekh-hmcts commented on src/main/java/uk/gov/hmcts/probate/model/ccd/caveat/request/CaveatData.java
> +
may as well remove this empty line

2019-06-25 13:00 UTC, kurt-uk commented on src/main/java/uk/gov/hmcts/probate/model/ccd/caveat/request/CaveatData.java
> +
👍

2019-06-25 15:39 UTC, merged